### ISSUE TITLE
UDD M’thly Insurance typo

### ISSUE THREAD

**Issue by Infinite-Actuary** [terence-lim/actuarialmath#1]
Hi 👋 Nice to meet you. I'm https://www.linkedin.com/in/carlcorder/ on LinkedIn and connected with you a while back.

I was reading through the docs and noticed a typo here:

https://github.com/terence-lim/actuarialmath-guide/blob/8078954dcd049ef9cf654d09c024886391094b35/docs/udd.ipynb#L25

![actuarialmath-guide_issue](https://github.com/terence-lim/actuarialmath/assets/30910135/92ad722d-65cb-483e-b08c-48daa06de56b)

I believe it should be the following:

$1+j=(1+i)^{2} \implies \big(1+\frac{j^{(m)}}{m}\big)^{m}=\big(1+\frac{i^{(m)}}{m}\big)^{2m} \implies j^{(m)}=\frac{1}{m}(i^{(m)})^{2}+2 \cdot i^{(m)}$

Note that:

$i=i^{(1)} \quad$ and $\quad j=j^{(1)}=\frac{1}{1}(i^{(1)})^{2}+2 \cdot i^{(1)}=i^2+2i$

$\therefore \quad j^{(m)} \cdot {}^{2}A^{(m)}_x  = j^{(1)} \cdot {}^{2}A^{(1)}_x = j \cdot {}^{2}A_x \implies \boxed{{}^{2}A^{(m)}_x=\dfrac{i^2+2i}{\frac{1}{m}(i^{(m)})^{2}+2 \cdot i^{(m)}} \cdot {}^{2}A^{}_x}$

**Comment by terence-lim** [comment]
Apologies my tardy reply:

Yes, the numerator (and also later for the continuous insurance formula) should indeed be $i^2 + 2i$, which is the new interest rate after doubling its force.

For the denominator, it should start as $(i^2 + i)^{(m)}$, which by applying the mthly compounding becomes $m[(1+i^2 + 2i)^{1/m}) - 1]$. But  I couldn't quite get that to be equal to the form of your denominator?

Greatly appreciate your correction and feedback.  I believe my python code (the double_force() and mthly() static methods in the Interest class) correctly implements the calculation, but is just my markdown document that needs revision.  Thanks

**Comment by Infinite-Actuary** [comment]
Oh interesting, I had never seen the $^{(m)}$ (m-thly rate operator) applied to multiple terms as it is in the expression $(i^{2}+2i)^{(m)}$. But that makes complete sense from a substitution perspective.

I believe our expressions are equivalent.

$(i^{2}+2i)^{(m)}=m \cdot \big((1+i)^{2/m}-1\big)=\frac{1}{m}(i^{(m)})^{2}+2 \cdot i^{(m)}$

Thanks for teaching me something new!
